### ISSUE TITLE
Hi, how do i reinstall this lesson after I forked it once? I deleted it due to some error...

### ISSUE THREAD

**Issue by albertoegomez** [learn-co-curriculum/ruby-lecture-fixing-our-broken-program#10]
Hi, 

How do i reinstall this lesson after I forked it once? I deleted it due to some error...

Thanks, 

Alberto

**Comment by Joll59** [comment]
@albertoegomez: Please ask questions using Slack or Ask A Question feature. 

For this problem in particular: 
If you've forked the lesson, you can clone it again from your repositories.
