### ISSUE TITLE
i am having a challenge opening this lesson in my terminal. please advise. 

### ISSUE THREAD

**Issue by albertoegomez** [learn-co-curriculum/ruby-lecture-fixing-our-broken-program#11]
Hi,
I initially forked and cloned this lesson then had trouble with it. I deleted the files under code/labs and then downloaded files from github and imported them in back to code/labs ... however when i tried opening it the program to complete the lab I got the following messages: Please advise on how best to next proceed. Thanks in advance. Alberto 

/ ♥ open ruby-lecture-fixing-our-broken-program-001-prework-web                
Couldn't get a file descriptor referring to the console                         
[23:23:23] labs                                                                 
// ♥ learn                                                                      
You don't appear to be in a Learn lesson's directory. Please cd to an appropriat
e directory and try again.

**Comment by Joll59** [comment]
I think the issue here is you are not in the proper directory to open that particular file.
Navigate into the proper directory in this case _code/labs_ then utilize the open command to open that particular folder. The same applies for utilizing the learn command.
